version: '3.7'

services:
  eureka:
    build:
      context: ..
      args:
        - PORT=${PORT}
      dockerfile: ./docker/Dockerfile
      target: prod
    image: ${IMAGE_NAME}:prod
    container_name: eureka
    restart: always
    depends_on:
      - eureka-db
    env_file:
      - ../.env
    environment:
      - TZ=${TZ}
      - WAIT_HOSTS=eureka-db:5432
    volumes:
      - ${LOGS_VOLUME}:/home/node/app/logs
    ports:
      - ${EXTERNAL_PORT}:${PORT}

  eureka-db:
    image: postgres:15
    container_name: eureka-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  eureka-adminer:
    image: adminer
    container_name: eureka-adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=eureka-db
      - TZ=${TZ}
    ports:
      - ${DB_MANAGER_PORT}:8080

networks:
  default:
    name: ${IMAGE_NAME}-network
